name: print-commit-message

on: [push]

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: commit message
        run: echo '${{ toJSON(github.event.commits[0].message) }}'
        shell: bash
        
